# Generated by Django 5.0.12 on 2025-05-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="durration",
            new_name="duration",
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("table", "reservation_time")},
        ),
    ]
